### PR TITLE
Add new constants for standard ruleset errors, resolves #5

### LINKED ISSUE #5: New constants for StandardRuleset errors
**What is the problem?**
Error messages are hardcoded strings throughout standard.go and standard_test.go

**What is the solution?**
Define new constants for possible errors, possibly in standard.go.

### PR DESCRIPTION
**Pull request by md-hexdrive**

### CODE REVIEW

**Comment by md-hexdrive** [comment]
Please let me know if there are any more changes I need to make.
Thanks!

**Comment by bvanvugt** [comment]
@md-hexdrive had a chance to look at this - it's a great start, and it's definitely better than what exists now.

I think we can take it one step further using this approach for error constants:
https://dave.cheney.net/2016/04/07/constant-errors

There's another example implementation here:
https://medium.com/@smyrman/writing-constant-errors-with-go-1-13-10c4191617

Using that technique, we could define a `RulesetError` type in ruleset.go, and then constants as `const` in standard.go. 

The key benefit of doing it this way is we can compare err directly, like this:
```go
if err == rules.ErrorTooManySnakes {
    ...
}
```

**Comment by bvanvugt** [comment]
@md-hexdrive let me know if you intend to make that change above. If so, we'll get this merged before January. 

If not, no worries. Just want to close off this PR.

**Comment by md-hexdrive** [comment]
Okay, Thanks for the Heads up. I'll get to work on this.

Sundays are the best days for me to complete this.

I should note that this is the first time I have programmed in Go.

Do you have any advice on what sort of development environment, I should program Go in?
The gofmt check was a bit of a pain for me when I was using GitHub's built-in editor.

**Comment by md-hexdrive** [comment]
Hey @bvanvugt !

Are these the changes you wanted me to make? 

I was able to find some time to work on this.

Please let me know where I should go with this from here.
Thanks
- @md-hexdrive 


P.S. The University of Waterloo's annual Hackathon, [Hack the North](https://hackthenorth.com/), is coming up in mid-January. This year it is going to be held virtually. 
I don't know if you guys are interested in participating in this with a Battlesnake event or not, or even if there is still time to get involved, but I thought you might be interested.

**Comment by bvanvugt** [comment]
@md-hexdrive wonderful, I'll take a look and get this merged now. 

Thanks for the heads up re: HTN. We know a few of the organizers, we'll see what we can do :)

**Review by bvanvugt — APPROVED** [review]
Looks good! Gonna merge, and tweak a little. Thanks!

**Comment by md-hexdrive** [comment]
You're Welcome!!! 
Out of curiosity, When will this code be running on play.battlesnake.com ?

**Comment by bvanvugt** [comment]
Likely shortly after the Winter Classic Tournament on the 19th.

**Pull request merged**
